#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WeatherApp_v2.Droid.Resource", IsApplication=true)]

namespace WeatherApp_v2.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::WeatherApp_v2.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::WeatherApp_v2.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::WeatherApp_v2.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::WeatherApp_v2.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::WeatherApp_v2.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::WeatherApp_v2.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::WeatherApp_v2.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::WeatherApp_v2.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::WeatherApp_v2.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::WeatherApp_v2.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::WeatherApp_v2.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::WeatherApp_v2.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::WeatherApp_v2.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::WeatherApp_v2.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::WeatherApp_v2.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::WeatherApp_v2.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::WeatherApp_v2.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::WeatherApp_v2.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::WeatherApp_v2.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::WeatherApp_v2.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::WeatherApp_v2.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int borderColor = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int grayish = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int screen_color = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_01d = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_01n = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_02d = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_02n = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_03d = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_04d = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_04n = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_09d = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_09n = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_10d = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_10n = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_11d = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_11n = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_13d = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_13n = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_50d = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_50n = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int RoundedCorners = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int splash = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int weather = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int weatherLogo = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int city_editText = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int city_textView = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int date_textView = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int description_textView = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int keyRow = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int location_textView = 2131034120;
			
			// aapt resource value: 0x7f05000e
			public const int mvxListView1 = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int myButton = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int progressBar1 = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int temperature_imageView = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int temperature_relativeLayout = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int temperature_textView = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int valueRow = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int main_layout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int multi_column = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int weather_details = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int splash = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[]
			{
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
